apiVersion: v2
name: isdalen-bank
description: Isdalen Bank — Bjorøy Bank instance
type: application
version: 0.1.13
appVersion: "1.4.21"

dependencies:
  - name: bjoroy-bank
    version: "0.12.43"
    repository: "oci://oci.bjoroy.me/bank"
