apiVersion: v2
name: fifth-network-instance
description: FIFTH Network — shared financial infrastructure
type: application
version: 0.1.3
appVersion: "0.2.3"

dependencies:
  - name: fifth-network
    version: "0.2.3"
    repository: "oci://oci.bjoroy.me/fifth"
