# Minoa Bank — instance overrides
# All other values inherit from the bjoroy-bank chart defaults

bjoroy-bank:
  global:
    instanceId: "minoa-bank"
    domain: "bjoroy.me"
    imageTag: "1.4.13"
    imageRegistry: "oci.bjoroy.me/bank"
    dbHost: "postgres-postgresql.database.svc.cluster.local"

  paymentEngine:
    centralBankUrl: "http://bragd-api.bragd-rtgs.svc.cluster.local:8095"
    bankId: "MINO"

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: minoa-bank.bjoroy.me
        paths:
          - path: /
            pathType: Prefix
      - host: minoa-bank-admin.bjoroy.me
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: minoa-bank-tls
        hosts:
          - minoa-bank.bjoroy.me
          - minoa-bank-admin.bjoroy.me
